import About from "@/components/About";
import Hero from "@/components/Hero";
import Head from "next/head";
import Project from "@/components/Project";
export default function Home() {
  return (
    <>
      <Head>
        <title>Justin Lien</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Hero section */}
      <div className="min-h-screen w-screen px-4 sm:px-16 lg:px-36 overflow-hidden">
        <Hero />

        {/* About section */}
        <About />

        {/* Project section */}
        <Project />
        {/* Contact section */}
      </div>
    </>
  );
}
